openapi: 3.0.0
info:
  version: '2102'
  title: MasterData/Attribution Management
  description: ''
servers:
  - url: /api
tags:
  - name: MasterData
paths:
  '/masterdatas/{type}':
    get:
      summary: Get All MasterData
      tags:
        - MasterData
      operationId: GetAllMasterData
      description: Gets a list of all available Master Data Attributes
      parameters:
        - name: type
          in: path
          required: true
          schema:
            type: string
          description: 'The Type of Master data. For example, Currency'
      responses:
        '200':
          description: >-
               By default, returns the list of MasterData filtered by type
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MasterData_OUTPUT_ALL'
              example:
                  type: Bundle
                  total: 1
                  entry:
                      id: aHR0cDovL3d3dy5pbm1pbmRjbG91ZC5jb20vYXBwbGljYXRpb24vc2NoZW1hLm93bCNBY2NvdW50VHlwZURpcmVjdA==
                      type: AccountType
                      uri: 'http://www.inmindcloud.com/application/schema.owl#AccountTypeDirect'
                      label: Direct
                      sequenceID: 1
                      objectName: Account Direct
                      objectId: AccountTypeDirect
                      objectExternalId: []
                      objectERPId: []
                      attributionImage: []
                      objectDateOfCreation: []
                      objectDateOfUpdate: []
                      attributionFactor: []
                      objectLastModifiedStateId: []
              
    post: 
      summary: Create MasterData
      tags:
        - MasterData
      parameters:
        - name: type
          in: path
          required: true
          schema:
            type: string
          description: 'The Type of Master data. For example, Currency'
      description: >-
        Creates a new Master Data attribute and returns the basic information of the Master Data.
      requestBody:
        description: Example of Request Payload as Resource
        content:
          application/json:
            schema:
              allOf:
                - $ref: '#/components/schemas/MasterData_CREATE_INPUT'
              example:
                objectName: test Account Type 2
                type: AccountType 
              required:
                - type
                - objectName
        required: true
            
      responses:
        '200':
          description: 'Returns the created object information'
          headers: {}
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MasterData_CREATE_OUTPUT'
              example:
                  id: aHR0cDovL3d3dy5pbm1pbmRjbG91ZC5jb20vYXBwbGljYXRpb24vc2NoZW1hLm93bCNBY2NvdW50VHlwZURpcmVjdA==
                  type: AccountType
                  uri: 'http://www.inmindcloud.com/application/schema.owl#AccountTypeDirect'
                  label: Direct
                  sequenceID: 1
                  objectName: Account Direct
                  objectId: AccountTypeDirect
                  objectExternalId: []
                  objectERPId: []
                  attributionImage: []
                  objectDateOfCreation: []
                  objectDateOfUpdate: []
                  attributionFactor: []
                  objectLastModifiedStateId: []
  '/masterdatas/{id}':
    delete:
      summary: Delete MasterData by id
      tags:
        - MasterData
      operationId: DeleteMasterData
      description: >-
        Delete data with given id
      parameters:
        - name: id
          in: path
          description: >-
            MasterData id.
          required: true
          schema:
            type: string
            format: base64-encoded
            example: >-
                aHR0cDovL2xvY2FsaG9zdDo4MDgwL2lzcy9BY2NvdW50VHlwZSNmZDUyZWJlMWIwNmE0ZWQ0OTg4YmE4NzNiMzRlMGEyNw==
      responses:
        '204':
          description: 'Returns empty response with no content'
  '/masterdatas/{type}/{id}':
    get:
      summary: Get MasterData By ID
      tags:
        - MasterData
      parameters:
        - name: type
          in: path
          required: true
          schema:
            type: string
            format: base64-encoded URI
            example: >-
                AccountType
        - name: id
          in: path
          required: true
          schema:
            type: string
            example: >-
              aHR0cDovL2xvY2FsaG9zdDo4MDgwL2lzcy9BY2NvdW50VHlwZSNmZDUyZWJlMWIwNmE0ZWQ0OTg4YmE4NzNiMzRlMGEyNw==
      responses:
        '200':
          description: 'Returns the details of the MasterData attribute'
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/MasterData_OUTPUT_ALL'
                example:
                    id: aHR0cDovL3d3dy5pbm1pbmRjbG91ZC5jb20vYXBwbGljYXRpb24vc2NoZW1hLm93bCNBY2NvdW50VHlwZURpcmVjdA==
                    type: AccountType
                    uri: 'http://www.inmindcloud.com/application/schema.owl#AccountTypeDirect'
                    label: Direct
                    sequenceID: 1
                    objectName: Account Direct
                    objectId: AccountTypeDirect
                    objectExternalId: []
                    objectERPId: []
                    attributionImage: []
                    objectDateOfCreation: []
                    objectDateOfUpdate: []
                    attributionFactor: []
                    objectLastModifiedStateId: []
          
    patch:
      summary: Update MasterData (change header data)
      tags:
        - MasterData
      parameters:
        - name: type
          in: path
          required: true
          schema:
            type: string
          description: ''
        - name: id
          in: path
          required: true
          schema:
            type: string
            format: base64-encoded
            example: >-
                aHR0cDovL2xvY2FsaG9zdDo4MDgwL2lzcy9BY2NvdW50VHlwZSNmZDUyZWJlMWIwNmE0ZWQ0OTg4YmE4NzNiMzRlMGEyNw==
      requestBody:
          description: MasterData object to be updated.
          content:
            application/json:
              schema:
                allOf:
                  - $ref: '#/components/schemas/MasterData_UPDATE_INPUT'
              example:
                  objectName: Test Account Type 1(Updated)
                  type: AccountType
      responses:
        '200':
          description: 'Returns the updated MasterData object'
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/MasterData_OUTPUT_ALL'
                example:
                    id: aHR0cDovL3d3dy5pbm1pbmRjbG91ZC5jb20vYXBwbGljYXRpb24vc2NoZW1hLm93bCNBY2NvdW50VHlwZURpcmVjdA==
                    type: AccountType
                    uri: 'http://www.inmindcloud.com/application/schema.owl#AccountTypeDirect'
                    label: Direct
                    sequenceID: 1
                    objectName: Account Direct
                    objectId: AccountTypeDirect
                    objectExternalId: []
                    objectERPId: []
                    attributionImage: []
                    objectDateOfCreation: []
                    objectDateOfUpdate: []
                    attributionFactor: []
                    objectLastModifiedStateId: []
  '/masterdatas/{type}/search':
    post:
      summary: Search MasterData
      tags:
        - MasterData
      parameters:
        - name: type
          in: path
          required: true
          schema:
            type: string
            description: ''
      requestBody:
        description: Example of Request Payload as Resource
        content:
          application/json:
            schema:
              allOf:
                - $ref: '#/components/schemas/MasterData_SEARCH_INPUT'
              required: 
                - type
              example:
                filter: objectName contains 'test'
        required: true
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MasterData_OUTPUT_ALL'
              example:
                type: Bundle
                total: 1
                entry:
                    id: aHR0cDovL3d3dy5pbm1pbmRjbG91ZC5jb20vYXBwbGljYXRpb24vc2NoZW1hLm93bCNBY2NvdW50VHlwZURpcmVjdA==
                    type: AccountType
                    uri: 'http://www.inmindcloud.com/application/schema.owl#AccountTypeDirect'
                    label: Direct
                    sequenceID: 1
                    objectName: Account Direct
                    objectId: AccountTypeDirect
                    objectExternalId: []
                    objectERPId: []
                    attributionImage: []
                    objectDateOfCreation: 1604635526590
                    objectDateOfUpdate: 1604635526640
                    attributionFactor: []
                    objectLastModifiedStateId: []
  '/masterdatas/{id}/locale':
    get:
      summary: Get MasterData Label
      tags:
        - MasterData
      description: 'Gets the locale attributes corresponding to the MasterData object'
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
            description: ''
      responses:
        '200':
          description: ''

components:
  schemas:
  
    MasterData_ID:
      type: object
      properties:
        id:
          type: string
          format: base64-encoded URI
          example: aHR0cDovL3d3dy5pbm1pbmRjbG91ZC5jb20vYXBwbGljYXRpb24vc2NoZW1hLm93bCNBY2NvdW50VHlwZURpcmVjdA==
        uri: 
          type: string
          example: >-
            'http://www.inmindcloud.com/application/schema.owl#AccountTypeDirect'
    
    MasterData_OBJECT_NAME:
      type: object
      properties:
        objectName:
          type: string
          example: New Account Type
      
    MasterData_OBJECT_ID:
      type: object
      properties:
        objectId:
          type: string
          example: a1652881275e4bc6b0bca89420b5434e
    
    MasterData_DATE_OF_CREATION:
      type: object
      properties:
        objectDateOfCreation:
          type: integer
          format: timestamp
          example: 1604635526590
    
    MasterData_DATE_OF_UPDATE:
      type: object
      properties:
        objectDateOfUpdate:
          type: integer
          format: timestamp
          example: 1604639345545
          
    MasterData_OUTPUT_ALL:
      allOf:
        - $ref: '#/components/schemas/MasterData_OUTPUT'
		
    MasterData_OUTPUT:
      type: object
      properties:
        id:
          type: string
          format: base64-encoded URI
          example: aHR0cDovL3d3dy5pbm1pbmRjbG91ZC5jb20vYXBwbGljYXRpb24vc2NoZW1hLm93bCNBY2NvdW50VHlwZURpcmVjdA==
        type:
          type: string
          example: AccountType
        uri:
          type: string
          example: 'http://www.inmindcloud.com/application/schema.owl#AccountTypeDirect'
        label:
          type: string
          example: Direct
        sequenceID:
          type: integer
          example: 1
        objectName:
          type: string
          example: Test Account 1
        objectId:
          type: string
          example: Test Account 1
        objectDateOfCreation:
          type: integer
          format: timestamp
          example: 1604635526590
        objectDateOfUpdate:
          type: integer
          format: timestamp
          example: 1604635526640
          
    MasterData_CREATE_INPUT:
      type: object
      properties:
        type:
          type: string
          example: "AccountType"
        objectName:
          type: string
          example: "Test Account Type"
          
    MasterData_CREATE_OUTPUT:
      allOf:
        - $ref: '#/components/schemas/MasterData_ID'
        - $ref: '#/components/schemas/MasterData_OBJECT_NAME'
        - $ref: '#/components/schemas/MasterData_OBJECT_ID'
        - $ref: '#/components/schemas/MasterData_DATE_OF_CREATION'
        - $ref: '#/components/schemas/MasterData_DATE_OF_UPDATE'
        - $ref: '#/components/schemas/MasterData_CREATE_INPUT'
        
    MasterData_UPDATE_INPUT:
      allOf:
        - $ref: '#/components/schemas/MasterData_CREATE_INPUT'
        
    MasterData_SEARCH_INPUT:
      type: object
      properties:
        type: 
          type: string
          description: Retrieve the opportunities in the system.
          example: Search
          default: 'Search'
        limit:
          type: integer
          description: Defines the maximum number of records that can be returned.
          example: 5
        offset:
          type: integer
          description: Defines the number of records that should be skipped. Default value is 0.
          default: 0
        filter:
          type: string
          example: ''
          description: The filter parameter. If keyword contains space, it must be enclosed betwen two apostrophe('). If keyword is URI, it must be url encoded
        sort:
          description: Defines the sorting of the result. 'ASC' for ascending and 'DESC' for descending order. Default order is objectName ASC
          type: array
          items:
            type: string
            example: 'objectName DESC'
        elements:
          type: object
          description: >-
            Sets the BDAs and BRAs that will be returned. id, type, uri , label and comment are included by default. If 'elements' is not specified, all the BDAs and BRAs will be returned.
          properties:
            bda:
              type: string
              description: >-
                Defines the requested BDAs that will be returned. If set as empty string, only id, type, uri , label and comment will be returned.
              example: 
                - objectName
                - objectId
            bra:
              type: string
              description: >-
                Defines the requested BRAs that will be returned. If set as empty string, no BRAs will be returned. Ensure the BRA array contains all the dependent resources that are defined in 'include'.
              example: 
                - includesAddress
 